### PR TITLE
feat: easily change network

### PR DESCRIPTION
**Pull request by Macxim**
Screen Shot 2022-01-24 at 8 25 08 AM

Screen Shot 2022-01-24 at 8 24 33 AM

### CODE REVIEW

**Comment by Macxim** [comment]
Screen Shot 2022-01-24 at 9 52 48 AM

**Comment by philipdesmedt** [comment]
@Macxim nice! I'll make this dynamic

**Comment by philipdesmedt** [comment]
@Macxim I think this is ready - could you try this?

**Comment by Macxim** [comment]
I'm getting this in console.

Screen Shot 2022-01-25 at 10 48 35 AM

**Comment by philipdesmedt** [comment]
@Macxim thx - is that on first load?

**Comment by philipdesmedt** [comment]
@Macxim any luck now?

**Pull request merged**
