### PR TITLE
feat: LP token staking

### PR DESCRIPTION
**Pull request by philipdesmedt**

### CODE REVIEW

**Comment by philipdesmedt** [comment]
@Macxim any ideas on these stake/unstake/claim buttons?

image

**Comment by nieldeckx** [comment]
Looks good, better to have APY calculations in FE. 

Proposal to visualise info and buttons:
Screenshot 2021-07-10 at 14 20 30

**Comment by philipdesmedt** [comment]
@nieldeckx nice! 

@Macxim what do you think?

**Comment by Macxim** [comment]
Mmmh, ideally actions should be grouped in the same place to avoid confusion, preferably on the far right for LTR locales. 

Basically it boils down to this:

- inline actions like we currently have (but 3 is already a lot IMO)
- hover actions: actions are hidden and only shown when hovering the row, reducing clutter
- menu actions: dedicated dropdown menu for each row where you put all the available actions

You can alternatively have a combination 1 and 3, that is keeping most important action inline and having secondary actions hidden behind a dropdown menu. 

More info here:

- https://ux.stackexchange.com/questions/26366/best-way-to-show-many-user-actions-for-table-rows
- http://www.jankoatwarpspeed.com/ultimate-guide-to-table-ui-patterns/

**Comment by philipdesmedt** [comment]
@Macxim should I merge and you improve it later or you wanna fix some small things on this branch?

**Comment by Macxim** [comment]
I guess you can merge. I'll have a look tomorrow or later this week. Good job! 💪

**Pull request merged**
