### PR TITLE
tweak: Vaults section redesign

### PR DESCRIPTION
**Pull request by Macxim**
Screenshot 2021-08-27 at 17-24-11 Arkadiko Finance

### CODE REVIEW

**Review by nieldeckx — APPROVED** [review]
Looks good!
Not sure if we can remove collateral-type.tsx @philipdesmedt ?

**Comment by philipdesmedt** [comment]
@nieldeckx yeah - need to investigate... not sure either

**Comment by Macxim** [comment]
@nieldeckx @philipdesmedt Can you check again to see if I didn't break everything? 🙃

**Review by philipdesmedt — APPROVED** [review]
This looks great to me.

**Comment by philipdesmedt** [comment]
@nieldeckx can you also check again and merge if good?

**Pull request merged**
