### PR TITLE
chore: upgrade @stacks/transactions and @stacks/connect

### PR DESCRIPTION
**Pull request by philipdesmedt**

### CODE REVIEW

**Comment by philipdesmedt** [comment]
@Macxim @nieldeckx 

I upgraded @stacks/transactions and @stacks/connect but now the "Connect Wallet" button throws an error. There's already a bug report on the Hiro web-wallet repo (https://github.com/hirosystems/stacks-wallet-web/issues/2495) but no activity on it. 

Not going to waste time on this until we get more info from the Hiro team. Not sure if this is a bug in the auth lib or something on our end.

**Comment by philipdesmedt** [comment]
@nieldeckx @Macxim this is now fixed with another package upgrade and ready for review!

**Comment by Macxim** [comment]
Awesome, will review ASAP. 💪

**Comment by philipdesmedt** [comment]
gonna merge this

**Pull request merged**
