### PR TITLE
Add Unclaimed Rewards to Vaults Overview

### PR DESCRIPTION
**Pull request by Macxim**
Screen Shot 2021-08-19 at 4 33 10 PM
Screen Shot 2021-08-19 at 4 35 30 PM

### CODE REVIEW

**Comment by philipdesmedt** [comment]
@Macxim sweet! ❤️

**Review by nieldeckx — APPROVED** [review]
Nice!

**Comment by Macxim** [comment]
I'm not sure it's working properly.

- I had to manually refresh the page when the transaction succeeded
- Even after claiming the rewards: when I go back to the Vaults Overview, after a while, I still have rewards to claim

**Comment by philipdesmedt** [comment]
@Macxim rewards are per block (i.e. every 30s) so they accumulate again probably as soon as you claim. I'll check

**Comment by philipdesmedt** [comment]
This works as intended. Merging this.

**Pull request merged**
