### PR TITLE
tweak: pay stability fee on minting USDA if enough balance

### LINKED ISSUE #38: Minting extra xUSD also tries to pay stability fees in same TX which fails if xUSD balance is 0
image

### PR DESCRIPTION
**Pull request by philipdesmedt**
Fixes #38 

There's two options:

1. This approach
2. Remove the paying of stability fee in the mint method

### CODE REVIEW

**Review by nieldeckx — COMMENTED** [review]
I prefer option 2 because:
- This is more transparent to the end user (otherwise we need to explain this extra logic in the UI)
- Our marketing page mentions the fee can be paid back whenever they want
- I get we want to push users to pay the stability fee asap. I think we can do so via the UI. In this implementation the user might not have enough USDA, or might just create a new vault if he does not want to pay the stability fee yet.

**Comment by philipdesmedt** [comment]
@nieldeckx okay, I'll just remove paying the stability fee!

**Comment by philipdesmedt** [comment]
@nieldeckx done

**Comment by philipdesmedt** [comment]
@nieldeckx this PR is not done yet, I need to accrue the stability fees, since the interest based on the minted amount has changed, will fix this

**Comment by philipdesmedt** [comment]
@nieldeckx done

**Comment by nieldeckx** [comment]
Alright, looks good.

**Pull request merged**
