### PR TITLE
feat: distribute missing LP staking rewards

### PR DESCRIPTION
**Pull request by nieldeckx**
Simple contract which can mint the missing rewards.

### CODE REVIEW

**Comment by nieldeckx** [comment]
@Macxim can you please update the UI?

@philipdesmedt this is ready for review. We can use the tests to calculate the amount of missing rewards. These numbers can be added to the Google sheet which will produce the map we need to enter in the contract.

**Comment by Macxim** [comment]
There you go:

Screen Shot 2021-11-09 at 2 46 16 PM

**Comment by nieldeckx** [comment]
Awesome! 👍

**Comment by nieldeckx** [comment]
Missed DIKO rewards according to tests in "arkadiko-stake-lp-rewards_test":
- wSTX/USDA:  376453.790682
- wSTX/DIKO:  112936.136346
- DIKO/USDA:  188226.894432

Used this doc as snapshot:
https://docs.google.com/spreadsheets/d/1aD-W9uhigKDuTMM9AmrefdBD6jm9rv1EtHYEGW7KhFM/edit#gid=274640655

To create the final list here:
https://docs.google.com/spreadsheets/d/1z_w7zEX8ma4eTw99Rhi7AzmOtRfpjARt6kI1Ky1FbRw/edit?usp=sharing

**Pull request merged**
