### PR TITLE
tweak: combine multiple stake read calls

### PR DESCRIPTION
**Pull request by nieldeckx**
The idea is to decrease the amount of RPC calls on the stake page. Combining 'get-pending-rewards' is not possible due to read limit.

If approved, we should:
1) Deploy the new contract
2) Test locally with mainnet
3) Deploy new FE

### CODE REVIEW

**Comment by Macxim** [comment]
Awesome!

**Comment by philipdesmedt** [comment]
I can deploy this in a bit

**Comment by philipdesmedt** [comment]
Still deploying the yield claims, but will get to this once the claims are ready 😬

**Comment by philipdesmedt** [comment]
This is deployed
https://explorer.stacks.co/txid/0x7deee59ae4bf919c2f1ede1eb6d5a67a7c69bb9a7d516a6c46b6509d218f6b7e?chain=mainnet

**Comment by philipdesmedt** [comment]
@nieldeckx epic fail :D
image

**Comment by nieldeckx** [comment]
@philipdesmedt damn, it worked locally.. Will make the update.

**Comment by philipdesmedt** [comment]
@nieldeckx test the read count with `clarinet console`

**Comment by nieldeckx** [comment]
@philipdesmedt v1-2 can be deployed :)

**Comment by nieldeckx** [comment]
Deployed v1-2: https://explorer.stacks.co/txid/0xed3fdace011b4f559f12995dcc465f3837001362615f09e60a0d5fcac7a20ee3?chain=mainnet

**Pull request merged**
