### PR TITLE
feat: dark theme 🌚✨

### PR DESCRIPTION
**Pull request by Macxim**
The much awaited feature is finally here. 🌙
Hope you like it!

Can you check all pages and see if I missed a spot?

Welcome to the dark side of the DIKO!

### CODE REVIEW

**Comment by philipdesmedt** [comment]
@Macxim awesome!

How do I toggle between light and dark mode? I don't see `ColorThemeToggle` being used anywhere?

**Comment by Macxim** [comment]
In the header, far right menu item.

**Comment by philipdesmedt** [comment]
Wasn't showing up. Talked to Maxime and we had to run `rm -rf node_modules && rm -rf yarn.lock && yarn && yarn dev` cause tailwind got upgraded.

**Review by philipdesmedt — CHANGES_REQUESTED** [review]
This looks good, execpt for the governance vote page

image

**Comment by Macxim** [comment]
Ah right, I missed that one. Thanks!

**Comment by Macxim** [comment]
@philipdesmedt Could you check now?

**Review by philipdesmedt — APPROVED** [review]
Great work!

**Pull request merged**
