### PR TITLE
feat:add a single button to add/remove liquidity

### PR DESCRIPTION
**Pull request by Macxim**
<p align="center">
Screen Shot 2021-07-01 at 3 50 03 PM
</p>

### CODE REVIEW

**Comment by nieldeckx** [comment]
I would not combine the "add/remove liquidity" button and the secondary information in the same light purple box. The information is linked to your current swap, while the new button is a different action. Something like this makes more sense to me:
Screenshot 2021-07-01 at 17 05 55

**Comment by Macxim** [comment]
@nieldeckx 
Yes, you are absolutely right. 

We could also have a button group like this at the top: 

image

What do you think?

**Comment by nieldeckx** [comment]
Yeah, that's probably better :)

**Comment by Macxim** [comment]
Alright!

**Comment by Macxim** [comment]
Since it's a link (that takes into account the current pair in the URL), it should look like so, and not like a button.
We can do the whole Pool overview and differentiation between Swap and Pool later.

Here it is, this should be enough for the short term and in the meantime we can focus on other things.

Screen Shot 2021-07-02 at 4 06 18 PM

**Pull request merged**
