### PR TITLE
refacto: add styled-icon component

### PR DESCRIPTION
**Pull request by Macxim**
This introduces a new component to wrap icons.
See `web/components/ui/styled-icon.tsx`.
Quite a few changes but this is for the best 😄

### CODE REVIEW

**Comment by Macxim** [comment]
I'll do a review myself later just to check I didn't miss any and I didn't mess up sizes/classes 🤓

**Comment by Macxim** [comment]
Just reviewed and couldn't find any issue. 💪

**Comment by philipdesmedt** [comment]
@Macxim can you fix merge conflicts? :D

**Comment by Macxim** [comment]
@philipdesmedt Done 🤓

**Comment by philipdesmedt** [comment]
@Macxim unfortunately you need to do it again after I merged the other PR 😅

**Comment by Macxim** [comment]
Done 💯

**Comment by philipdesmedt** [comment]
image

Computer says no
@Macxim just fix & squash merge :)

**Pull request merged**
