### PR TITLE
tweak: add more info about DIKO/stDIKO and update Unstake DIKO modal

### LINKED ISSUE #353: When unstaking DIKO, it is not clear you need to unstake your stDIKO amount and not the DIKO earned until then
Pretty high prio since this is confusing UX

@Macxim

### PR DESCRIPTION
**Pull request by Macxim**
Closes #353 

### Unstake DIKO
Screen Shot 2021-11-16 at 12 37 38 PM

### Tweaks in Stake DIKO block
Screen Shot 2021-11-16 at 12 37 20 PM

### CODE REVIEW

**Comment by nieldeckx** [comment]
@Macxim looks good! 
As extra I've added the amount of DIKO to get for 1 stDIKO.

**Comment by Macxim** [comment]
Updated the design a bit.
Screen Shot 2021-11-16 at 3 48 06 PM

**Review by nieldeckx — APPROVED** [review]
Great!

**Comment by philipdesmedt** [comment]
This is a great addition.. I'm only concerned about the amount of RPC's we do on the Stake page.. it's already loading a very long time at peak times (when US wakes up and during the day)... 

We should look into optimising some calls.

**Comment by nieldeckx** [comment]
Once https://github.com/arkadiko-dao/arkadiko/pull/359 merged, we can finish this PR.

**Comment by Macxim** [comment]
Feedback from [Heat on Discord](https://discord.com/channels/827123370520215562/853249022478254081/911173672906129429): 

>To be even more clear, stDIKO could have info about your current percentage of the pool. This would then explain how the DIKO amount shown can actually go down when your percentage goes down due to the pool's expansion "while you were out."

**Review by philipdesmedt — APPROVED** [review]
This is good for me.

IDK if we wanna incorporate Heat's feedback as pasted above by @Macxim?

**Pull request merged**
