### PR TITLE
Stacking cycle info

### PR DESCRIPTION
**Pull request by nieldeckx**
Get stacking info from stacking.club API

### CODE REVIEW

**Comment by philipdesmedt** [comment]
Awesome 😍 

Will try it asap.

**Comment by philipdesmedt** [comment]
@nieldeckx nice work
Got some code comments - will do a PR review

@Macxim 
image

can you find a nice home for this and give it some design love?

**Comment by Macxim** [comment]
Will do later this week!

**Comment by philipdesmedt** [comment]
@Macxim cool thx.. btw the dates are not exact, should be something like this

image

**Comment by Macxim** [comment]
Too much?

Screen Shot 2021-07-12 at 4 31 40 PM
Screen Shot 2021-07-12 at 4 35 07 PM

**Comment by philipdesmedt** [comment]
@Macxim great start

The first one is too much in your face for me.
The second I like, might be my favorite.
The third one is easy to digest but very similar to the tables we already have.

@nieldeckx thoughts?

**Comment by nieldeckx** [comment]
Agree with @philipdesmedt. 
Instead of the start date, it might be more useful to show the end date. The end date is when yields for a new vault start, or when a user can stop stacking and withdraw funds.

**Comment by Macxim** [comment]
We can also use that indigo panel I created in other pages. I added a placeholder by the way. Check it out!

https://user-images.githubusercontent.com/1909957/125361711-9cfd9a80-e365-11eb-8c1f-aef8a24f1444.mov

**Comment by philipdesmedt** [comment]
@Macxim nice yeah! the placeholder is really good - should use that for all loading states.

**Comment by Macxim** [comment]
Fancier? 😃 

Screen Shot 2021-07-13 at 10 08 27 AM

**Comment by philipdesmedt** [comment]
@Macxim nice! LGTM

**Comment by Macxim** [comment]
Pushed.

**Comment by nieldeckx** [comment]
Wow, very nice!!

**Comment by philipdesmedt** [comment]
Aight nice, gonna merge this for now. Not sure if we're visualising all the correct data, but at least we are showing some PoX stuff now.

**Pull request merged**
