### PR TITLE
feat: improve speed of Stake page

### PR DESCRIPTION
**Pull request by philipdesmedt**

### CODE REVIEW

**Comment by Macxim** [comment]
Awesome! Really good job. 🚀 
Can you maybe run `prettier "./components/stake.tsx" --write` when you're done?

**Review by Macxim — APPROVED** [review]

**Comment by philipdesmedt** [comment]
@Macxim done, I added a local binary for prettier so we can run `./node_modules/prettier/bin-prettier.js "./components/stake.tsx" --write` in the web folder

**Comment by Macxim** [comment]
`prettier` was already in devDependencies though, so you could just run `yarn lint:prettier:fix` and it should have linted all files.
We could also add a pre-commit hook for this.

**Comment by philipdesmedt** [comment]
@Macxim right, I forgot :D I will remove this again

**Pull request merged**
