### PR TITLE
fix: calculate staking APYs based on each staking pool

### PR DESCRIPTION
**Pull request by nieldeckx**
APY is now calculated for each pool.

### CODE REVIEW

**Review by philipdesmedt — APPROVED** [review]
Code looks good. Will test this on the front-end and merge.

We will need some loading states, since we are waiting for >5 requests now, but I'll handle that

**Comment by philipdesmedt** [comment]
@nieldeckx I divided all APY's by 10^5 since I think that was needed?

Also added loading state

**Comment by nieldeckx** [comment]
Love the loading state.

@philipdesmedt I don't think you needed to divide the APY's again? When fetching the total tokens staked we already divide by 1000000. 

Simple example for DIKO pool:
- Total staking reward for year 1 = 23500000 * 0.1 = 2350000 (see const totalStakingRewardsYear1)
- User stakes 2350000 DIKO (see totalDikoStaked where we already divide by 1000000)
- APY = 2350000/2350000 = 1 = 100% (user indeed doubles his amount over 1 year)

**Comment by philipdesmedt** [comment]
@nieldeckx not sure... the APYs were like 41700000% :P seems really high?

will double check before merging

**Comment by philipdesmedt** [comment]
@nieldeckx you were right, rolled back the divisions. Gonna merge

**Pull request merged**
