### PR TITLE
Mint: UI improvements

### PR DESCRIPTION
**Pull request by Macxim**
|Before|After|
|---|---|
|bef|aft|

### CODE REVIEW

**Comment by philipdesmedt** [comment]
🙇‍♂️

**Comment by Macxim** [comment]
What should we do about xUSD last price?

**Comment by philipdesmedt** [comment]
@Macxim should be fixed at $1, for now at least. Later when we go to mainnet, we will probably get a real-time price from the swap

**Review by philipdesmedt — APPROVED** [review]
Looks great man! Thanks for fixing my shitty code :)

**Pull request merged**
