### PR TITLE
feat: add liquidity through the UI

### PR DESCRIPTION
**Pull request by Macxim**
Mostly static at the moment but here it is:

As usual, nothing is set in stone, feedback welcome!

### CODE REVIEW

**Comment by philipdesmedt** [comment]
Don't have much to comment on this, maybe a few small things:

- At the bottom, you can see "Your pool tokens" & share.. would these be the current ones that you already have added (before potentially adding more) or based on the ones you're selecting?
- Pooled xUSD & Pooled DIKO is the global current pool I guess?

**Comment by Macxim** [comment]
Ah yeah, sorry it's not clear in the screenshot.
- The block with `Your pool tokens & share` would be filled in as the user fills the tokens input
- This displays the pair that is currently selected

**Comment by nieldeckx** [comment]
Looks good!

**Review by nieldeckx — APPROVED** [review]

**Comment by Macxim** [comment]
Do we also need a link at the top leading to the current open positions?

**Comment by Macxim** [comment]
We need to change the copy for the tooltips in `Pool tokens` and `Pool share`.

**Comment by philipdesmedt** [comment]
@Macxim we can do the liquidity positions in another PR, but seems low priority right now.

**Pull request merged**
