### PR TITLE
tweak: swap and pool improvements

### LINKED ISSUE #313: Improve input when adding liquidity
- Best would be if user can either change input for both tokens. 
- Prevent user from creating transaction if not enough funds

Screenshot 2021-10-26 at 17 21 41

### PR DESCRIPTION
**Pull request by Macxim**
Closes #313 and #291

- keep tabs clickable while loading, rework placeholder
- fix slippage tolerance Auto button conditional classes 
- improve loading states for add liquidity
- improve loading state for pool position 
- add loading states for remove liquidity

### CODE REVIEW

**Comment by Macxim** [comment]
#291 should be taken care of now.

@nieldeckx @philipdesmedt Do you want to look into #313? 

> Best would be if user can either change input for both tokens.
> Prevent user from creating transaction if not enough funds

We don't have to do it here. This can be done separately.
Feel free to adjust description and related issues so that it doesn't close them automatically when this PR is merged.

**Comment by nieldeckx** [comment]
Great. Fixed some bugs and added the possibility for the user to also change tokenY input.
Can you also add loading states to "remove-swap-liquidity" please?

**Comment by Macxim** [comment]
Will do! Thanks for the fixes 🤩

**Comment by Macxim** [comment]
Should be ready for review now @philipdesmedt and @nieldeckx.

**Review by nieldeckx — APPROVED** [review]
Great work, looks good!

**Pull request merged**
