### PR TITLE
fix: LP tokens wSTX-DIKO and wSTX-USDA being staked by users are lost [0F-ARK-006]

### PR DESCRIPTION
**Pull request by philipdesmedt**
See https://github.com/0f/0f-ark-2108/issues/7

### CODE REVIEW

**Review by nieldeckx — APPROVED** [review]
Ok. 
(Have asked auditor for more info on this, because in our tests it was working.)

**Comment by philipdesmedt** [comment]
@nieldeckx Ludo has replied - tests were for the other pair that was fixed already :)

Should we add some additional tests?

**Comment by nieldeckx** [comment]
Damn, stupid mistake. Will add tests for all pools.

**Comment by nieldeckx** [comment]
@philipdesmedt added more tests and fixed an issue in the emergency-withdraw method

**Comment by philipdesmedt** [comment]
@nieldeckx good catch 😬

**Pull request merged**
