### PR TITLE
Add atALEX as collateral type

### PR DESCRIPTION
**Pull request by YannisDC**
Governance proposal to add atALEX as collateral type:

- Stability Fee: 4%
- Debt Ceiling: 250,000 USDA
- Liquidation Penalty: 20%
- LTV: 25%

### CODE REVIEW

**Review by philipdesmedt — CHANGES_REQUESTED** [review]

**Comment by nieldeckx** [comment]
FYI: in order for the liquidations to work we need to add the new token in `arkadiko-liquidation-rewards-v1-1` via the method  `update-reward-tokens`

**Comment by philipdesmedt** [comment]
I think everything is ready here

@Macxim could you add some CSS for the right atALEX colors?

image

**Comment by Macxim** [comment]
@philipdesmedt It was already there. Just needed to add the correct class. I did it 👍 Let's go 🚀

**Comment by philipdesmedt** [comment]
@Macxim thanks!

@nieldeckx gonna merge this - are we still using another branch to make production builds?

**Comment by nieldeckx** [comment]
@philipdesmedt just merged the new auction-engine branch. So pull in master and you should be good.

**Pull request merged**
