### PR TITLE
Add `Max.` button on input fields where you can enter an amount

### LINKED ISSUE #41: Add MAX button to all inputs
image

### PR DESCRIPTION
**Pull request by Macxim**
Fixes #41

### CODE REVIEW

**Comment by Macxim** [comment]
Let's leave out for now the `Add Swap Liquidity` and `Remove Swap Liquidity`pages. This can be implemented later.

**Comment by Macxim** [comment]
Vaults

|Before|After|
|---|---|
|Screen Shot 2021-06-23 at 11 50 54 AM|Screen Shot 2021-06-23 at 11 50 34 AM|

**Comment by Macxim** [comment]
Mint extra xUSD

|Before|After|
|---|---|
|Screen Shot 2021-06-23 at 11 53 15 AM|Screen Shot 2021-06-23 at 11 53 08 AM|

**Comment by Macxim** [comment]
Burn xUSD

|Before|After|
|---|---|
|Screen Shot 2021-06-23 at 11 54 54 AM|Screen Shot 2021-06-23 at 11 55 04 AM|

**Comment by Macxim** [comment]
Deposit extra collateral

|Before|After|
|---|---|
|Screen Shot 2021-06-23 at 11 56 39 AM|Screen Shot 2021-06-23 at 11 56 30 AM|

**Comment by Macxim** [comment]
@philipdesmedt Can you check if I miss any?

Also, I need someone to take over to finish what should happen when clicking on that `Max.` button.
I left empty functions at the moment.

**Comment by philipdesmedt** [comment]
@Macxim great - I'll finish the implementation

**Comment by nieldeckx** [comment]
> Vaults
> 
> Before	After
> Screen Shot 2021-06-23 at 11 50 54 AM	Screen Shot 2021-06-23 at 11 50 34 AM
> Alignment is a bit weird here. Maybe it should be left aligned for all or add a property to choose left/right.

Agree that the alignment is a bit strange. Would just align everything to the left. Not critical at all.

Looks great though, good job!

**Comment by philipdesmedt** [comment]
@Macxim I think I fixed everything in this PR

**Pull request merged**
