### PR TITLE
Add empty state component

### PR DESCRIPTION
**Pull request by Macxim**
Feel free to changes the icons and/or the copy

#### Governance

Screen Shot 2021-07-12 at 10 32 02 AM

#### Auctions
Screen Shot 2021-07-12 at 10 32 12 AM

#### Vaults
Screen Shot 2021-07-12 at 10 37 48 AM

### CODE REVIEW

**Comment by nieldeckx** [comment]
Looks good!  Icons look a bit fat to me, would scale down by ~50%. But thats personal preference :)

**Review by nieldeckx — APPROVED** [review]

**Comment by Macxim** [comment]
It actually looks quite big when there are no description, you're right. I'll update it.

**Review by philipdesmedt — APPROVED** [review]
LGTM 

Downsize a bit and we can merge. Great work!

**Comment by Macxim** [comment]
Done 😉

**Comment by philipdesmedt** [comment]
@Macxim slick work broski! merging this

**Pull request merged**
