### PR TITLE
feat: implement multiple custom provider support

### PR DESCRIPTION
**Pull request by philipdesmedt**

### CODE REVIEW

**Comment by philipdesmedt** [comment]
@nieldeckx @Macxim could you review please?

**Review by Macxim — APPROVED** [review]
Works well. Looks good to me.

**Comment by Macxim** [comment]
Also, nice dependencies upgrade 💪

**Comment by nieldeckx** [comment]
Was able to connect Leather wallet and broadcast a tx. Looks good!

**Pull request merged**
